version: '3'

services:
  api:
    build: .
    container_name: "api"
    ports:
      - '80:3000'
    volumes:
      - /var/www/node_modules
      - .:/var/www
    environment:
      - NODE_ENV=development
      - PORT=3000
    links:
      - db
    depends_on:
      - db
  db:
    image: mongo:latest
    container_name: "db"
    restart: always
    volumes:
      - ./data/db:/data/db
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_DATABASE=search-api
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
